import type{Word,State,Question,QType,WordProgress,Status}from'./types';import{defaultProgress}from'./storage';
const iso=()=>new Date().toISOString().slice(0,10);const addDays=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};const mix=<T,>(a:T[])=>[...a].sort(()=>Math.random()-.5);
function seeded(seed:number){let t=seed+0x6D2B79F5;return()=>{t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
export function dailySet(words:Word[],count:number,day:number,used:number[]){const pool=words.filter(w=>!used.includes(w.id)),r=seeded(day*7919+count*101),rank=pool.map(w=>({w,r:r()})).sort((a,b)=>a.r-b.r),out:Word[]=[];for(const x of rank){if(out.length===count)break;if(!out.some(w=>w.word[0]===x.w.word[0])&&out.filter(w=>w.category===x.w.category).length<2)out.push(x.w)}for(const x of rank)if(out.length<count&&!out.some(w=>w.id===x.w.id))out.push(x.w);return out}
const get=(s:State,id:number)=>s.progress[id]||defaultProgress();
const option=(right:string,pool:string[])=>{let o=mix([right,...pool.filter(x=>x&&x.toLowerCase()!==right.toLowerCase())]).filter((x,i,a)=>a.findIndex(y=>y.toLowerCase()===x.toLowerCase())===i).slice(0,4);return{options:mix(o),answer:0,right}}
export function makeQuestion(w:Word,type:QType,all:Word[]):Question{let prompt='',right='',bad:string[]=[];if(type==='definitionWord'){prompt=w.definition;right=w.word;bad=w.distractors.filter(x=>!w.synonyms.includes(x)&&x.toLowerCase()!==w.word.toLowerCase())}else if(type==='wordDefinition'){prompt=`“${w.word}” kelimesinin doğru açıklaması hangisidir?`;right=w.definition;bad=mix(all.filter(x=>x.id!==w.id)).slice(0,6).map(x=>x.definition)}else if(type==='fillBlank'){prompt=w.fillBlank;right=w.word;bad=w.distractors.filter(x=>x.toLowerCase()!==w.word.toLowerCase())}else if(type==='synonym'){prompt=`“${w.word}” kelimesine en yakın anlam hangisidir?`;right=w.synonyms[0]||w.definition;bad=[...w.antonyms,...w.distractors]}else if(type==='antonym'){prompt=`“${w.word}” kelimesinin karşıt anlamı hangisidir?`;right=w.antonyms[0];bad=[...w.synonyms,...w.distractors]}else{prompt=`“${w.word}” kelimesinin Türkçe anlamı hangisidir?`;right=w.turkish;bad=mix(all.filter(x=>x.id!==w.id)).slice(0,6).map(x=>x.turkish)}let o=option(right,bad.length>=3?bad:mix(all.filter(x=>x.id!==w.id)).slice(0,8).map(x=>x.word));return{wordId:w.id,type,prompt,options:o.options,answer:o.options.indexOf(right)}}
export function buildChallenge(kind:'daily'|'risky'|'favorites'|'master',words:Word[],s:State){let pool:Word[]=[];const due=words.filter(w=>{const p=get(s,w.id);return p.nextReview&&p.nextReview<=iso()});if(kind==='risky')pool=words.filter(w=>get(s,w.id).status==='risky');else if(kind==='favorites')pool=words.filter(w=>s.favorites.includes(w.id));else if(kind==='master')pool=words.filter(w=>['master','masterReview'].includes(get(s,w.id).status));else{const fresh=s.todayIds.map(id=>words.find(w=>w.id===id)).filter(Boolean) as Word[];const risky=words.filter(w=>get(s,w.id).status==='risky');const master=words.filter(w=>['master','masterReview'].includes(get(s,w.id).status));const weightedFav=words.filter(w=>s.favorites.includes(w.id));pool=[...fresh,...fresh,...mix(risky).slice(0,6),...mix(due).slice(0,4),...mix(master).slice(0,2),...(s.settings.includeFavorites?mix(weightedFav).slice(0,2):[])];}
if(!pool.length)pool=s.todayIds.map(id=>words.find(w=>w.id===id)).filter(Boolean) as Word[];const max=kind==='daily'?s.settings.challengeSize:10,target=Math.min(max,new Set(pool.map(x=>x.id)).size*2||max);let counts:Record<number,number>={},qs:Question[]=[],types:QType[]=['definitionWord','wordDefinition','fillBlank','synonym','antonym','turkish'];for(const w of [...pool,...mix(pool)]){if(qs.length>=target)break;if((counts[w.id]||0)>=2)continue;let used=qs.filter(q=>q.wordId===w.id).map(q=>q.type),available=types.filter(t=>!used.includes(t)&&!(t==='antonym'&&!w.antonyms.length));let type=available[Math.floor(Math.random()*available.length)]||'definitionWord';qs.push(makeQuestion(w,type,words));counts[w.id]=(counts[w.id]||0)+1}return mix(qs)}
export function recordAnswer(s:State,wordId:number,correct:boolean,unknown:boolean,type:QType){const p={...get(s,wordId)},day=iso();p.seen++;if(correct){p.correct++;p.correctStreak++;if(!p.daysCorrect.includes(day))p.daysCorrect=[...p.daysCorrect,day]}else{p.wrong++;if(unknown)p.unknown++;p.correctStreak=0}p.accuracy=Math.round(p.correct/p.seen*1000)/10;p.lastSeen=day;p.questionTypes=[...new Set([...p.questionTypes,type])];const intervals=[1,3,7,14,30,60];p.reviewStage=correct?Math.min(p.reviewStage+1,5):0;p.nextReview=addDays(correct?intervals[p.reviewStage]:1);let status:Status=p.status;if(p.seen>=3&&p.accuracy<60)status='risky';else if(p.accuracy>95&&p.seen>=10&&p.daysCorrect.length>=4&&p.questionTypes.length>=3&&p.correctStreak>=3){status='master';p.masterDate=p.masterDate||day}else if(status==='risky'&&p.seen>=5&&p.accuracy>=60&&p.correctStreak>=2)status='learning';else if(status==='new')status='learning';else if(p.accuracy>=85&&status!=='master')status='strong';p.status=status;return{...s,progress:{...s.progress,[wordId]:p}}}
export const stats=(s:State)=>({master:Object.values(s.progress).filter(p=>p.status==='master').length,risky:Object.values(s.progress).filter(p=>p.status==='risky').length});