import type{Word,State,Question,QType,Status}from'./types';
import{defaultProgress}from'./storage';
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const shuffle=<T,>(a:T[])=>[...a].sort(()=>Math.random()-.5);
const clean=(v:string)=>v.trim().toLocaleLowerCase('en-US');
function seeded(seed:number){let t=seed+0x6D2B79F5;return()=>{t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
export function dailySet(words:Word[],count:number,day:number,used:number[]){const pool=words.filter(w=>!used.includes(w.id)),rnd=seeded(day*7919+count*101),rank=pool.map(w=>({w,r:rnd()})).sort((a,b)=>a.r-b.r),out:Word[]=[];for(const x of rank){if(out.length===count)break;if(!out.some(w=>w.word[0].toLowerCase()===x.w.word[0].toLowerCase())&&out.filter(w=>w.category===x.w.category).length<2)out.push(x.w)}for(const x of rank)if(out.length<count&&!out.some(w=>w.id===x.w.id))out.push(x.w);return out}
const progress=(s:State,id:number)=>s.progress[id]||defaultProgress();
function makeOptions(correctAnswer:string,candidates:string[],targetWord:string){const banned=new Set([clean(targetWord),clean(correctAnswer)]);const unique=candidates.filter(Boolean).map(x=>x.trim()).filter((x,i,a)=>!banned.has(clean(x))&&a.findIndex(y=>clean(y)===clean(x))===i);const distractors=shuffle(unique).slice(0,3);if(distractors.length<3)throw new Error('Not enough valid distractors');return shuffle([correctAnswer,...distractors])}
function otherWords(all:Word[],w:Word){return shuffle(all.filter(x=>x.id!==w.id))}
export function makeQuestion(w:Word,type:QType,all:Word[]):Question{let prompt='',correctAnswer='',candidates:string[]=[];const others=otherWords(all,w);
 if(type==='definitionWord'){prompt=`Which word matches this definition?\n\n${w.definition}`;correctAnswer=w.word;candidates=[...w.distractors,...others.map(x=>x.word)]}
 else if(type==='wordDefinition'){prompt=`Which is the correct definition of “${w.word}”?`;correctAnswer=w.definition;candidates=others.map(x=>x.definition)}
 else if(type==='fillBlank'){prompt=`Complete the sentence:\n\n${w.fillBlank}`;correctAnswer=w.word;candidates=[...w.distractors,...others.map(x=>x.word)]}
 else if(type==='synonym'){prompt=`Which option is closest in meaning to “${w.word}”?`;correctAnswer=w.synonyms[0];candidates=[...w.antonyms,...w.distractors,...others.flatMap(x=>x.synonyms)]}
 else if(type==='antonym'){prompt=`Which option is opposite in meaning to “${w.word}”?`;correctAnswer=w.antonyms[0];candidates=[...w.synonyms,...w.distractors,...others.flatMap(x=>x.antonyms)]}
 else{prompt=`What is the Turkish meaning of “${w.word}”?`;correctAnswer=w.turkish;candidates=others.map(x=>x.turkish)}
 const options=makeOptions(correctAnswer,candidates,w.word);return{wordId:w.id,type,prompt,options,correctAnswer}}
function weightedTypes(index:number,w:Word,used:QType[]):QType[]{const english:QType[]=['definitionWord','definitionWord','definitionWord','fillBlank','fillBlank','synonym','wordDefinition','antonym'];let candidates=index%10===9?(['turkish']as QType[]):english;candidates=candidates.filter(t=>!used.includes(t)&&!(t==='antonym'&&!w.antonyms.length)&&!(t==='synonym'&&!w.synonyms.length));return candidates.length?candidates:['definitionWord']}
export function buildChallenge(kind:'daily'|'risky'|'favorites'|'master'|'review',words:Word[],s:State){let pool:Word[]=[];const due=words.filter(w=>{const p=progress(s,w.id);return p.nextReview&&p.nextReview<=today()});if(kind==='review')pool=due;else if(kind==='risky')pool=words.filter(w=>progress(s,w.id).status==='risky');else if(kind==='favorites')pool=words.filter(w=>s.favorites.includes(w.id));else if(kind==='master')pool=words.filter(w=>['master','masterReview'].includes(progress(s,w.id).status));else{const fresh=s.todayIds.map(id=>words.find(w=>w.id===id)).filter(Boolean)as Word[],risky=words.filter(w=>progress(s,w.id).status==='risky'),master=words.filter(w=>['master','masterReview'].includes(progress(s,w.id).status)),favs=words.filter(w=>s.favorites.includes(w.id));pool=[...fresh,...fresh,...shuffle(risky).slice(0,6),...shuffle(due).slice(0,4),...shuffle(master).slice(0,2),...(s.settings.includeFavorites?shuffle(favs).slice(0,2):[])]}
 if(!pool.length)pool=s.todayIds.map(id=>words.find(w=>w.id===id)).filter(Boolean)as Word[];const unique=[...new Map(pool.map(w=>[w.id,w])).values()],target=Math.min(kind==='daily'?s.settings.challengeSize:10,unique.length*2);const expanded=shuffle([...unique,...unique]),counts:Record<number,number>={},qs:Question[]=[];
 for(const w of expanded){if(qs.length>=target)break;if((counts[w.id]||0)>=2)continue;const used=qs.filter(q=>q.wordId===w.id).map(q=>q.type),types=weightedTypes(qs.length,w,used),type=types[Math.floor(Math.random()*types.length)];try{const q=makeQuestion(w,type,words);if(q.options.includes(q.correctAnswer)&&new Set(q.options.map(clean)).size===4){qs.push(q);counts[w.id]=(counts[w.id]||0)+1}}catch{const q=makeQuestion(w,'wordDefinition',words);qs.push(q);counts[w.id]=(counts[w.id]||0)+1}}
 return qs}
export function recordAnswer(s:State,id:number,correct:boolean,unknown:boolean,type:QType){const p={...progress(s,id)},date=today();p.seen++;if(correct){p.correct++;p.correctStreak++;if(!p.daysCorrect.includes(date))p.daysCorrect=[...p.daysCorrect,date]}else{p.wrong++;if(unknown)p.unknown++;p.correctStreak=0}p.accuracy=Math.round(p.correct/p.seen*1000)/10;p.lastSeen=date;p.questionTypes=[...new Set([...p.questionTypes,type])];const intervals=[1,3,7,14,30,60];p.reviewStage=correct?Math.min(p.reviewStage+1,5):0;p.nextReview=addDays(correct?intervals[p.reviewStage]:1);let status:Status=p.status;if(p.seen>=3&&p.accuracy<60)status='risky';else if(p.accuracy>95&&p.seen>=10&&p.daysCorrect.length>=4&&p.questionTypes.length>=3&&p.correctStreak>=3){status='master';p.masterDate=p.masterDate||date}else if(status==='risky'&&p.seen>=5&&p.accuracy>=60&&p.correctStreak>=2)status='learning';else if(status==='new')status='learning';else if(p.accuracy>=85&&status!=='master')status='strong';p.status=status;return{...s,progress:{...s.progress,[id]:p}}}
export const stats=(s:State)=>({master:Object.values(s.progress).filter(p=>p.status==='master').length,risky:Object.values(s.progress).filter(p=>p.status==='risky').length});

export const dueWords=(words:Word[],s:State)=>words.filter(w=>{const p=s.progress[w.id];return !!(p?.nextReview&&p.nextReview<=today())});
